### ISSUE TITLE
Fan mode: "ASIC controlled"

### ISSUE THREAD

**Issue by Marchcat2008** [rdugan/iceriver-alph-oc#10]
Hello.
In firware 0.84, after rebooting the ASIC, the fan speed in the "ASIC controlled" fan mode always drops to zero. The fan speed setting is not saved. It is necessary to apply the fan settings again and again, otherwise the temperature jumps instantly.
Please check the fan control settings.
Moreover, I noticed that until the overclocking settings are applied, the fan control settings are not saved either.
Thank you.

**Comment by rdugan** [comment]
ASIC controlled is exactly that - controlled by the asic, not my firmware.  There's nothing i can do about it, and it's precisely the reason i created a new, better mode in Temp target
