### ISSUE TITLE
All my AL0 went to 0 hash rate

### ISSUE THREAD

**Issue by Lsfarm440** [rdugan/iceriver-alph-oc#11]
I have 4 AL0 overclocked with the last version and all of them went to 0 hash rate, have other without overclock and they are ok. Just got back to factory firmware and hash rate is normal again.

**Comment by RainBitcoins** [comment]
And I bet your overclock setting numbers are identical in all 4 yes?

**Comment by Lsfarm440** [comment]
No, two @260 mhz, 65 mv and the other two @150 mhz, 30 mv

**Comment by rdugan** [comment]
Sounds like either you put them to sleep, or you OCd too much.  If they work fine at 0 offsets, it's clearly the latter.
