### ISSUE TITLE
Problem with low chip voltage 

### ISSUE THREAD

**Issue by mucwendel** [rdugan/iceriver-alph-oc#2]
When i set no oc. Values, the chip voltage is lower than original and hashrate dropps below 300.

I test 20mv to reach the original chip voltage and hashrate comes back to normal.

**Comment by AlexNauta** [comment]
Do you have any additional cooling? I have only seen the Al0 drop that far when you cool it too much, chip temps really like the 60/70 degrees-C. Maybe higher offset results in higher temperature, and therefore, a more normal hashrate.

**Comment by RainBitcoins** [comment]
My AL0 hashes best at 76c on the hot side

**Comment by mucwendel** [comment]
Ok, maybe too cold.
I'm actually in China and the al0 is in Germany.
A friend put a cooling shroud (120mm usb fan) at one end and remove the front and back plates for me.
But the setup of oc voltage is not showing correct. 
It says depending on base 370mv. But at 0mv it just shows 345mv in the graph. 
So actually I use 20mhz and 40mv and the graph shows... 

375mv
645mhz
60deg c
413gh 2h range

But the chip temperature is around 60 maybe far too cold

**Comment by AlexNauta** [comment]
The Al0 does not like being cooled, I also disconnected the 120mm fan I added. So you would be good when you remove the schroud & 120mm fan.

**Comment by RainBitcoins** [comment]
I took my cooling shroud off... Works much better

**Comment by mucwendel** [comment]
I only wonder about the extra mV.
Maybe the comment of 370mV as standard is wrong or it's not adding to 370. When i adjust 60mV i get 388mB in the graph.
370mV + 60mV should end up at 430mV.
Can you confirm by check and post your settings?

**Comment by RainBitcoins** [comment]
![20240914_114733](https://github.com/user-attachments/assets/17d8f030-c88f-4b0d-9964-7eec3e5af5a4)
![20240914_114719](https://github.com/user-attachments/assets/5a0ed4e1-7174-450a-9d91-b8552cec20b6)

**Comment by mucwendel** [comment]
Ok, thanks.
I see your chip voltage also don't match with the oc settings.
Just s small bug 😂

But as I haven't do any modification to the power board heatsink i should wait to be back in Germany.

I did the mods alo on my 2x  ks0 ultra and works good.

**Comment by RainBitcoins** [comment]
Yes I've done the mods on my other kso's as well... Hence why I had some shrouds kicking around. But the AL0's works much better without the shroud. Took me about 8 hours of playing around with it to figure this out lol.. So your currently in China eh? I was just in Shenzhen making a large asic purchase for our farm back here in Canada. Be safe and have a nice trip.

**Comment by mucwendel** [comment]
Thanks

**Comment by rdugan** [comment]
> Just s small bug 😂

It's not a bug.  That's how electronics work.  Please read the [documentation](https://github.com/rdugan/iceriver-alph-oc?tab=readme-ov-file#graphing-of-chip-metrics-and-longer-term-hashrates)

**Comment by mucwendel** [comment]
I checked the Doku. Still don't understand why e. g. 370mv +60mV will not show as 430mV.

**Comment by rdugan** [comment]
It's 2 sentences below where i linked:

> _Please note that real-time voltage will never match your setting - drivers under load experience voltage drop, meaning the running voltage will always be below your voltage setting, with more load causing a greater drop._

**Comment by mucwendel** [comment]
Ok, anyway thanks for the oc mod

**Comment by mucwendel** [comment]
I've another question, and do not know how to solve.
I got another al0 and connect it to the net in order to put the oc fw on.
As I could not find it in the network i check the unit. was hot so must be mining on the standard address.
So I pressed the reset button and i could not find it. Than disconnect power, hold the reset button and power up.
Maybe i was not waiting long enough and did another power cycle.

Actual situation is...
both LED green and red are constantly on. No reaction to reset button. Not showing up in the network :-(

Question to rdugan, do you have any idea to bring it back to life?

**Comment by RainBitcoins** [comment]
Pbfarmer provides support to his OC firmware... Your current issue is your own stupidity. Email Iceriver for support.

**Comment by mucwendel** [comment]
> Pbfarmer provides support to his OC firmware... Your current issue is your own stupidity. Stop bothering him, I'm sure he's a very busy dude. Email Iceriver for support.

Thank you for the friendly reply.
Helps a lot
