### ISSUE TITLE
AL0 drops the OC. says it cant connect to Dev Pool

### ISSUE THREAD

**Issue by Tonykostansek** [rdugan/iceriver-alph-oc#3]
Any idea why i cant connect to the Dev pool.  the Asic dropped the OC back to stock.

**Comment by Tonykostansek** [comment]
How to return to stock Firmware

**Comment by rdugan** [comment]
Same as always.  The big red button that says 'Restore factory settings'  Or the hardware button for 30s.

If it's a temporary network interruption or pool outage, the OC may be removed, but will be reapplied when the situation clears.  Otherwise, it's likely a problem with your network setup, and you should read the documentation (specifically ['Known Issues' section](https://github.com/rdugan/iceriver-alph-oc?tab=readme-ov-file#known-issues)

**Comment by Tonykostansek** [comment]
if i apply any OC the miner hash drops signifantly.  not sure how folks are getting 20 to 50 mhz over clock.  I cant even get one to work.

**Comment by Tonykostansek** [comment]
its not really going to add up to much anyway i just dont want to pay a dev fee if in not getting a hash boost.

**Comment by Tonykostansek** [comment]
your interface is aewsome though.

**Comment by rdugan** [comment]
> if i apply any OC the miner hash drops signifantly. not sure how folks are getting 20 to 50 mhz over clock. I cant even get one to work.

I don't understand - the first issue you reported would suggest you were able to OC.  And if your hashrate is dropping from OC, [it means you don't have enough voltage](https://github.com/rdugan/iceriver-alph-oc?tab=readme-ov-file#tuning).

**Comment by Tonykostansek** [comment]
Can you give a good baseline to start with?  I assumed the OC was diasabled due to the Dev issue. but now any overclock kills hash. Mhz and Volts at zero and i get about 380 to 430 over an hour.

**Comment by rdugan** [comment]
Like i said, the inaccessible dev fee is either a temporary issue, in which case its not disabling anything (permanently), or it's something you need to fix in your network, in which case OC won't ever work until you fix it

There is no baseline - you need to follow the tuning process explained in the docs i just linked.

And I'm not sure what you mean by 'over an hour', but the 2hr hashrate is the only thing that provides a low enough variance to fully understand OC effects.  This is also explained in the documentation

**Comment by Tonykostansek** [comment]
can i ping the dev server from the network to see if its active?

**Comment by rdugan** [comment]
it's always active...  it's just vipor

**Comment by Tonykostansek** [comment]
i took it home last night and tried it there.  Im getting about 420 average now.  I had to crank up the voltage to get the clock speed to work.  I guess mine was running at a low voltage.  You have the base line at 370mv.  Mine was running about 340.
clock speed is 50 and voltage is 20 and getting a 2 hours average of 420.
this sound like its inline with the typical senario.

**Comment by rdugan** [comment]
That's not really typical.  50mhz should get you 432ghs on the 2hr (+/- ~1-2%).  And 20mv for that is excessive from what i've seen so far.  And voltage readings never match the setting.  All of this is covered in the documentation, so I highly recommend reading through it.
