### ISSUE TITLE
50% Fee?

### ISSUE THREAD

**Issue by hanjo1980** [rdugan/iceriver-alph-oc#6]
Only 50% of Hash-Rate arrived at the pool with 0.8.3!

**Comment by RainBitcoins** [comment]
Wait longer or switch pools.

**Comment by hanjo1980** [comment]
Nope, that's not the problem!

**Comment by rdugan** [comment]
i'm looking into this w/ someone else right now... it might be a fee bug that is affecting maybe 5% of users.  

Which pool were you using?

**Comment by hanjo1980** [comment]
Humpool, and I got the hint from a other miner, who is also affected.

5 of 5 machines have this issue.

**Comment by hanjo1980** [comment]
5 of 5 machines has this issue.

**Comment by rdugan** [comment]
yeah other two people i've heard from were using humpool as well.  i'm testing it rn, but not seeing the issue yet, but it's early.

extensive testing was done on vipor and herominers - try one of those.

**Comment by rdugan** [comment]
@hanjo1980 any luck?  i'm not able to reproduce this on humpool.  can you send me (pbfarmer) a friend request on discord?

**Comment by hanjo1980** [comment]
Hi, unfortunately it doesn't work because you don't accept friend requests. You have to ask me: hanjo6489

**Comment by rdugan** [comment]
It's only happening if you have backup pools configured.  Just delete those pool configs until i release a fix.

**Comment by senesees** [comment]
This is happening to a few people (& me) so I looked into the fees, i think people deserve to know where the fee goes to & they should be able to monitor it in the firmware, this is the pool where the fee is collected, there are a few high hashrate, definitely not 1%:
[1EduqpYUBXYzotjL2o3Tw9EDS3CwHdpjoUmNkTMA5AGg2](https://vipor.net/miner/ALPH/1EduqpYUBXYzotjL2o3Tw9EDS3CwHdpjoUmNkTMA5AGg2/alph)

I would probably not use this firmware until there is some sort of monitor for the fee

**Comment by rdugan** [comment]
@senesees I'm not sure what you're 'looking into'.  Of course the fee goes to me.  And I already stated above that it's happening to about 5% of people (machines).  The previous release was always available as a backup.  And the cause of the bug, and fix, is also now documented here, as well as in the release notes, and every discord channel available.

The 'monitor' for the fee is your pool hashrate.  I've even explained in detail in the documentation how to best measure it.  If you don't want to use the firmware, nobody is forcing you to.  You're always free to build your own firmware.  Everyone else who has been using my firmware for months knows they're getting a steal for the thousands of hours of work and support I've put into these.

**Comment by senesees** [comment]
With this "bug", you are stealing money from people and if they are unaware, you could be stealing from them for the whole duration they have the firmware installed.
With a proper monitor in place for the fee, it would make people more aware and give them peace of mind that the fee is actually 1%.

**Comment by rdugan** [comment]
The monitor is your pool measurement.  If you think I'm stealing, then why tf would you trust any other number I give you?

Just don't use it.

**Comment by senesees** [comment]
Just a suggestion :) 
People like to know where their money(fee) is going and if its accurate.

The pool measurements are not always accurate.

**Comment by RainBitcoins** [comment]
Are you new to mining? Do you think Pbfarmer is some newb who's come out of nowhere? 
I highly doubt he would be so stupid as to steal from his users. He has a reputation to uphold and its very good one at that. Bugs happen, and in the grand scheme of things 1% is nothing. I would pay for a no de fee option of there was one, but in the long run even at 1% it works out to be cheaper than paying a dev fee.

**Comment by rdugan** [comment]
> The pool measurements are not always accurate.

The fee measurement is literally the inverse of the pool measurement.  If the pool measurement isn't accurate, than the fee measurement cannot be more accurate.  In fact, it's way worse, as accuracy is literally a function of the number of samples, and the number of samples in 99% of your hashrate is two orders of magnitude higher than the number of samples in 1% of your hashrate.

**Comment by senesees** [comment]
Yes you are right.
I'm not saying its an intentional bug, just saying it's probably frustrating some people.

And solution: to see fee shares.

**Comment by rdugan** [comment]
Fees do not always go to the same pool as the users.  And even when they do, the difficulty is likely different.  So share counts are essentially meaningless to 99% of people.

**Comment by senesees** [comment]
Okay, the fee hashrate then w/e

**Comment by rdugan** [comment]
You're literally going in circles now.  I've explained it as best I can here.  Read the documentation, use the pool to measure the hashrate, or just don't use the firmware.

**Comment by senesees** [comment]
List of units greatly exceeding 1% right now:
Worker: MDAxMDAwQTY3MzAwMjgx, Hashrate: 231.51 GH/s
Worker: MDAxMDAwQTY3MzAwMTUy, Hashrate: 218.99 GH/s
Worker: MDAxMDAwQTY3MzAwNEFF, Hashrate: 259.91 GH/s
Worker: MDAxMDAwQTY3MzAwNEQy, Hashrate: 226.01 GH/s
Worker: MDAxMDAwQTY3MzAwQzQw, Hashrate: 285.87 GH/s
Worker: MDAxMDAwQTY3MzAwQzRD, Hashrate: 284.04 GH/s
Worker: MDAxMDAwQTY3MzAwREVC, Hashrate: 180.81 GH/s
Worker: MDAxMDAwQTY3MzAwRjBG, Hashrate: 283.74 GH/s
Worker: MDAxMDAwQTY3MzAwRURB, Hashrate: 274.57 GH/s
Worker: MDAxMDAwQTY3MzAxMEY2, Hashrate: 277.93 GH/s
Worker: MDAxMDAwQTY3MzAxMjBD, Hashrate: 214.10 GH/s
Worker: MDAxMDAwQTY3MzAyMDU3, Hashrate: 244.95 GH/s
Worker: MDAxMDAwQTY3MzAyMjE5, Hashrate: 240.67 GH/s
Worker: MDAxMDAwQTY3MzAyNkE1, Hashrate: 256.25 GH/s
Worker: MDAxMDAwQTY3MzAyOTFD, Hashrate: 198.22 GH/s
Worker: MDAxMDAwQTY3MzAyQUYx, Hashrate: 237.62 GH/s

Total: 3915.19 GH/s

You don't think this is concerning?

**Comment by rdugan** [comment]
Great.  So only 3.38% of people.  Thanks for confirming.  WTF do you want me to do about it.  I've already literally been up until 6am working with people on the other side of the world to identify and fix the problem.

**Comment by senesees** [comment]
You are stealing from people, intentional or not.

**Comment by rdugan** [comment]
Dude, just stop using my fw and go away.  I'm tired of your trolling.

**Comment by senesees** [comment]
Yeah awareness is trolling...

**Comment by rdugan** [comment]
Fixed in release v0.8.4
