### ISSUE TITLE
In version 0.83 hashrate shows twice as low

### ISSUE THREAD

**Issue by Marchcat2008** [rdugan/iceriver-alph-oc#7]
First я want say thank you for your work. It's real cool firmware.
But I returned to the 0.82 version, because with the 0.83 firmware on the pools the hashrate shows twice as low and the real income has decreased by half (((
After rolling back to the old firmware the hashrate shows the same both on the pool and in the dashboard.

**Comment by RainBitcoins** [comment]
You need to remove any backup pools in your miner settings... Only have one pool in there. It's a bug that he's currently working on to fix.

**Comment by rdugan** [comment]
this has been fixed in v0.8.4 which was just released.
